version: "3.8"

services:
  scratch:
    image: busybox:latest
    deploy:
      replicas: 0
    networks:
      - public

networks:
  public:
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.16.200.0/24
